[package]
name = "hoi4save"
version = "0.1.6-pre"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
exclude = ["/assets/*", "/fuzz/*"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rakaly/hoi4save.git"
description = "Ergonomically work with HOI4 saves"
keywords = ["hoi4", "ironman"]
categories = ["parsing"]

[dependencies]
jomini = "0.14.1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
zip = { version =  "0.5", default-features = false, features = ["deflate"] }
attohttpc = "0.17"

[profile.test]
opt-level = 3
lto = "thin"

[profile.bench]
lto = true
codegen-units = 1

[profile.release]
lto = true
codegen-units = 1
